Voinova.Alyona
kystyn/OS_Labs_SPbPU_2021 pull request #10
Opened 2021-10-25 11:18 UTC by pikabol88

2021-10-31 10:57 UTC, kystyn requested changes
Это пока начало ревью. Я дочитал только до Parser.h и не успел запустить
Можете пока исправлять эти ошибки. Я закончу ревью ближе к ночи

2021-10-31 10:57 UTC, kystyn commented on Voinova.Alyona/lab1/Daemon.cpp
> +    } catch(std::exception const& e) {
Вы не совсем правильно поняли концепт. Смысл был в том, чтобы заключить в блок try вызов Daemon::init и остальных функций, которые кидают такие фатальные исключения, и отловить их в мэйне. При этом нет необходимости возвращать булев флаг и проверять его. Вы же кинули исключение внутри функции, поймали внутри функции, и в итоге все равно возвращаете true/false. Нужно переделать

2021-10-31 10:57 UTC, kystyn commented on Voinova.Alyona/lab1/Daemon.cpp
> +    delete result;
1. Если result -- динамический массив, его надо уджалять не так. Судя по документации ваш способ вообще не особо должен работать, т. к. вы передаёте вторым аргументом realpath-а null (https://www.opennet.ru/man.shtml?topic=realpath&category=3&russian=0)

2021-10-31 10:57 UTC, kystyn commented on Voinova.Alyona/lab1/Daemon.cpp
> +        fs::path destFile = dst/p.filename();
Вы используете как std::filesystem, так и unix systemcalls. выбирайте что-то одно

2021-10-31 10:57 UTC, kystyn commented on Voinova.Alyona/lab1/Parser.cpp
> +            throw std::runtime_error("Couldn't parse line " + std::to_string(i));
Зачем тут блок catch? Он, получается, присоединяет "Couldn't parse line " к строке исключения, которое вы кинули и тут поймали. Надо просто кинуть runtime_error на 28 строке и ловить в месте, где вызываете parseConfig

2021-10-31 10:57 UTC, kystyn commented on Voinova.Alyona/lab1/Parser.cpp
> +        return result;
Та же ошибка, что и выше

2021-10-31 10:57 UTC, kystyn commented on Voinova.Alyona/lab1/Parser.cpp
> +    _grammar = {
Лучше сделать грамматику консткнтной, чтобы случайно не поменять по пути

2021-10-31 19:32 UTC, pikabol88 commented on Voinova.Alyona/lab1/Parser.cpp
> +    _grammar = {
Исправлено

2021-10-31 19:32 UTC, pikabol88 commented on Voinova.Alyona/lab1/Parser.cpp
> +        return result;
Исправлено

2021-10-31 19:32 UTC, pikabol88 commented on Voinova.Alyona/lab1/Parser.cpp
> +            throw std::runtime_error("Couldn't parse line " + std::to_string(i));
Исправлено

2021-10-31 19:32 UTC, pikabol88 commented on Voinova.Alyona/lab1/Daemon.cpp
> +        fs::path destFile = dst/p.filename();
Исправлено

2021-10-31 19:33 UTC, pikabol88 commented on Voinova.Alyona/lab1/Daemon.cpp
> +    } catch(std::exception const& e) {
Единственный catch теперь находится в main

2021-10-31 19:34 UTC, pikabol88 commented on Voinova.Alyona/lab1/Daemon.cpp
> +    delete result;
Исправлено

2021-11-01 08:47 UTC, kystyn approved these changes
Всё ок, работа зачтена

2021-11-01 08:48 UTC, merged