Anikin
kystyn/OS_Labs_SPbPU_2021 pull request #13
Opened 2021-10-26 11:38 UTC by Nika-Keks

Добрый день, отправляю первую работу

2021-11-01 09:38 UTC, kystyn requested changes
Как указать несколько папок? По остальной функциональности вопросов нет

2021-11-01 09:38 UTC, kystyn commented on Anikin/laba1/build.sh
> +    echo `g++ -std=c++2a src/*.cpp -o $bin_dir/$name`
а зачем тогда CMakeLists?

2021-11-01 09:38 UTC, kystyn commented on Anikin/laba1/src/cfg_parser.cpp
> +    return (*value_it).second;
value_it->second :)

2021-11-01 09:38 UTC, kystyn commented on Anikin/laba1/src/daemon.cpp
> +            _inst = new daemon(cfg);
а где удаляете? можно же было использовать shared_ptr

2021-11-01 09:38 UTC, kystyn commented on Anikin/laba1/src/disck_monitor.cpp
> +#define BUFFER_SIZE (sizeof(struct inotify_event) + NAME_MAX + 1)
Дефайны в C++ лучше не использовать

2021-11-01 09:38 UTC, kystyn commented on Anikin/laba1/src/disck_monitor.cpp
> +    std::unique_ptr<dm_event> event_ptr(reinterpret_cast<dm_event*>(new char[BUFFER_SIZE]));
вообще не понял, что тут происходит/
1. Вы выделяете память под inotify_event в динамической памяти. Зачем? он занимает совсем немного места
2. Вы конструируете его от строки, хотя там куча полей
3. Вы потом конвертируете его опять в C-строку
4. Вы создаете память под строку фиксированного размера в динамической памяти

Короче, чё-то тут вы намудрили, я не понял. Объясните или переделайте (лучше и то и то)

2021-11-02 09:52 UTC, Nika-Keks commented on Anikin/laba1/build.sh
> +    echo `g++ -std=c++2a src/*.cpp -o $bin_dir/$name`
cmake я сипользовал при разработке, а потом забыл добавить в игнор
Сборочный скрипт написал напрямую через gcc, мне казалось через него проще
В следующих работах буду использовать cmake

2021-11-02 09:53 UTC, Nika-Keks commented on Anikin/laba1/src/cfg_parser.cpp
> +    return (*value_it).second;
Справедливо)

2021-11-02 09:54 UTC, Nika-Keks commented on Anikin/laba1/src/daemon.cpp
> +            _inst = new daemon(cfg);
Наверное даже нужно было 
Исправлю

2021-11-02 09:55 UTC, Nika-Keks commented on Anikin/laba1/src/disck_monitor.cpp
> +#define BUFFER_SIZE (sizeof(struct inotify_event) + NAME_MAX + 1)
Исправлю

2021-11-02 10:03 UTC, Nika-Keks commented on Anikin/laba1/src/disck_monitor.cpp
> +    std::unique_ptr<dm_event> event_ptr(reinterpret_cast<dm_event*>(new char[BUFFER_SIZE]));
Идея заключалась в том, чтобы спрятать от disk_monitor буфер типа char*, чтобы он манипулировал только inotify_event*
Но как-то вышло не очень красиво
Для этого стоило напимать класс-обертку над inotify_event, но, мне показалось, это будет лешним
Исправлю, сделаю проще

2021-11-02 10:43 UTC, Nika-Keks commented
Для того чтобы указать несколько папок нужно перечислить из в конфиге через " ; "
dm_folders=/home/path1;/home/path2

2021-11-06 11:11 UTC, kystyn commented on Anikin/laba1/src/disck_monitor.cpp
> +    std::unique_ptr<dm_event> event_ptr(reinterpret_cast<dm_event*>(new char[BUFFER_SIZE]));
Так в inotify_event-е итак есть этот буфер

2021-11-06 11:15 UTC, kystyn reviewed
Всё ок

2021-11-06 11:15 UTC, kystyn commented on Anikin/laba1/src/daemon.cpp
> +    return _inst.get();
ну вообще по-хорошему и отдавать тогда надо shared_ptr. потому что если бы это было не static поле, которое удалится в любом случае самым последним, то овнер указателя, полученного через shared_ptr::get() мог бы получить неприятность в виде невалидного C-style указателя, потому что счетчик указателей в вашем shared_ptr равен единице. Если хочется отдать с правами наблюдателя, без права редактирования то есть, то можно использовать weak_ptr

2021-11-06 11:15 UTC, merged