Ovechkin Danil Lab1
kystyn/OS_Labs_SPbPU_2021 pull request #14
Opened 2021-10-26 19:01 UTC by OvechkinDanil

Вариант 6

2021-11-01 14:18 UTC, kystyn requested changes
1. После запуска демона терминал продолжает висеть, вы не выходите из родительского процесса. При этом детский процесс работает, в т.ч. в другом терминале, с ним  всё хорошо
2. По сигналу SIGHUP  конфиг перечитывается (по логам), но при этом удаляются файлы из старой директории

2021-11-01 14:18 UTC, kystyn commented on Ovechkin.Danil/lab1/ConfigParser.cpp
> +    for (int i = 0; i < (int)tokens.size(); i++) {
size_t i и никаких C-style casts

2021-11-01 14:18 UTC, kystyn commented on Ovechkin.Danil/lab1/Daemon.cpp
> +    for (auto& path: std::filesystem::directory_iterator(fullpath)) {
Либо везде unix systemcalls, либо std::filesystem

2021-11-04 07:06 UTC, OvechkinDanil commented on Ovechkin.Danil/lab1/ConfigParser.h
> +    std::map<std::string , ConfigParams> tokens =
Хорошо, исправлю

2021-11-04 07:06 UTC, OvechkinDanil commented on Ovechkin.Danil/lab1/ConfigParser.cpp
> +    for (int i = 0; i < (int)tokens.size(); i++) {
Исправлю

2021-11-04 07:06 UTC, OvechkinDanil commented on Ovechkin.Danil/lab1/Daemon.cpp
> +    for (auto& path: std::filesystem::directory_iterator(fullpath)) {
Исправлю

2021-11-10 09:53 UTC, OvechkinDanil commented on Ovechkin.Danil/lab1/ConfigParser.h
> +    std::map<std::string , ConfigParams> tokens =
Исправил

2021-11-10 09:53 UTC, OvechkinDanil commented on Ovechkin.Danil/lab1/ConfigParser.cpp
> +    for (int i = 0; i < (int)tokens.size(); i++) {
Исправил

2021-11-10 09:53 UTC, OvechkinDanil commented on Ovechkin.Danil/lab1/Daemon.cpp
> +    for (auto& path: std::filesystem::directory_iterator(fullpath)) {
Вроде бы во всех местах исправил

2021-11-11 14:10 UTC, kystyn requested changes
Висит два процесса в терминале. Причина в том, что у вас нет блока кода, в который после форка попадёт родительский процесс. Когда вы добавите этот блок, то в нём спокойно можно делать exit/return/etc и всё будет ок

2021-11-14 07:55 UTC, OvechkinDanil commented
> Висит два процесса в терминале. Причина в том, что у вас нет блока кода, в который после форка попадёт родительский процесс. Когда вы добавите этот блок, то в нём спокойно можно делать exit/return/etc и всё будет ок Всё остальное ок

Исправил

2021-11-18 15:33 UTC, kystyn approved these changes

2021-11-18 15:34 UTC, kystyn commented
-2 балла за косяки и задержку

2021-11-18 15:34 UTC, merged