Antonov.aleksei
kystyn/OS_Labs_SPbPU_2021 pull request #21
Opened 2021-11-07 19:04 UTC by sqrtyyy

2021-11-07 20:46 UTC, kystyn requested changes
К сожалению, программа не запустилась: возвращено значение 1. Пути в конфиге сделал все валидными, не помогло. У меня на этом компьютере,к сожалению, проблемы с сислогом, я не могу посмотреть, что написалось в лог. Постараюсь посмотреть завтра на другом компьютере

2021-11-07 20:46 UTC, kystyn commented on Antonov.Aleksei/lab1/src/ConfigParser.h
> +private:
зачем вы перед каждой переменной указываете модификатор доступа? это не java

2021-11-07 20:46 UTC, kystyn commented on Antonov.Aleksei/lab1/src/ConfigParser.h
> +class ConfigParser
этот класс вообще не описывает состояние. тогда зачем вообще класс? это можно оформить как набор функций в пространстве имён. ну либо реализовывать такую архитектуру, в которой вообще появляется смысл класса парсера

2021-11-07 20:46 UTC, kystyn commented on Antonov.Aleksei/lab1/CMakeLists.txt
> +add_executable(${PROJECT_NAME} daemon_main.cpp ${SRC})
а почему у вас все исходники в src, а вот мэин отдельно?

2021-11-07 20:46 UTC, kystyn commented on Antonov.Aleksei/lab1/daemon_main.cpp
> +    return EXIT_FAILURE;
ну хоть какое-нибудь сообщение оставили бы. хоть в командной строке, хоть в логе

2021-11-07 20:46 UTC, kystyn commented on Antonov.Aleksei/lab1/src/Daemon.cpp
> +    m_configParams.push_front(lineParams);
Интересное решение использовать forward_list. Обычно дефолтно все юзают vector, а вы, скорее всего, специально полезли на cppreference и почитали про этот контейнер. Значит, вас, видимо, чем-то сильно не устроил вектор. Мне искренне интересно, чем. И почему именно forward_list? А не unordered_set, например?

2021-11-07 20:46 UTC, kystyn commented on Antonov.Aleksei/lab1/src/Daemon.cpp
> +  if(loadConfig(configFilePath) != RC::SUCCESS)
иногда хромают пробелы после ключевых слов

2021-11-07 20:46 UTC, kystyn commented on Antonov.Aleksei/lab1/src/Daemon.cpp
> +bool Daemon::copyFilesFromDir(const string& srcDir, const string& dstDir,
да, можно так. а можно ловить исключение там, где вызываете copyFilesFromDir и в том же блоке catch писать соотвтетсвюущее сообщение в лог. так проще и короче.

2021-11-07 20:46 UTC, kystyn commented on Antonov.Aleksei/lab1/src/Daemon.cpp
> +bool Daemon::cleanDir(const std::string& path) {
замечание, аналогичное сделанному в предыдущем методе

2021-11-07 20:46 UTC, kystyn commented on Antonov.Aleksei/lab1/src/Daemon.cpp
> +    m_instance = new Daemon;
а удаляете где?

2021-11-11 14:25 UTC, kystyn commented
Nov 11 17:25:11 dka-OptiPlex-790 ANTONOV_DAEMON: Initialization started
Nov 11 17:25:11 dka-OptiPlex-790 ANTONOV_DAEMON: Is not inited
Nov 11 17:25:11 dka-OptiPlex-790 ANTONOV_DAEMON: Is not inited
Nov 11 17:25:11 dka-OptiPlex-790 ANTONOV_DAEMON: Resetting PID 28678
Nov 11 17:25:11 dka-OptiPlex-790 ANTONOV_DAEMON: PID set 28739
Nov 11 17:25:11 dka-OptiPlex-790 ANTONOV_DAEMON: Config file can not be opened
Nov 11 17:25:11 dka-OptiPlex-790 ANTONOV_DAEMON: Loading config file failed
Nov 11 17:25:11 dka-OptiPlex-790 ANTONOV_DAEMON: Is not inited

Вот лог

2021-11-11 14:28 UTC, kystyn commented
Ваш демон требует абсолютный путь до конфига, это надо исправить. Тем не менее, даже с абсолютным путём получаю вот это

Nov 11 17:26:59 dka-OptiPlex-790 ANTONOV_DAEMON: Initialization started
Nov 11 17:26:59 dka-OptiPlex-790 ANTONOV_DAEMON: Is not inited
Nov 11 17:26:59 dka-OptiPlex-790 ANTONOV_DAEMON: Is not inited
Nov 11 17:26:59 dka-OptiPlex-790 ANTONOV_DAEMON: Resetting PID 28739
Nov 11 17:26:59 dka-OptiPlex-790 ANTONOV_DAEMON: PID set 28805
Nov 11 17:26:59 dka-OptiPlex-790 ANTONOV_DAEMON: Parsing config error 3
Nov 11 17:26:59 dka-OptiPlex-790 ANTONOV_DAEMON: Loading config file failed
Nov 11 17:26:59 dka-OptiPlex-790 ANTONOV_DAEMON: Is not inited
Nov 11 17:27:01 dka-OptiPlex-790 ANTONOV_DAEMON: Initialization started
Nov 11 17:27:01 dka-OptiPlex-790 ANTONOV_DAEMON: Is not inited
Nov 11 17:27:01 dka-OptiPlex-790 ANTONOV_DAEMON: Is not inited
Nov 11 17:27:01 dka-OptiPlex-790 ANTONOV_DAEMON: Resetting PID 28805
Nov 11 17:27:01 dka-OptiPlex-790 ANTONOV_DAEMON: PID set 28810
Nov 11 17:27:01 dka-OptiPlex-790 ANTONOV_DAEMON: Parsing config error 2
Nov 11 17:27:01 dka-OptiPlex-790 ANTONOV_DAEMON: Loading config file failed
Nov 11 17:27:01 dka-OptiPlex-790 ANTONOV_DAEMON: Is not inited

Конфиг:
/home/dka/me/antonov/OS_Labs_SPbPU_2021/Antonov.Aleksei/lab1/srcFiles;/home/dka/me/antonov/OS_Labs_SPbPU_2021/Antonov.Aleksei/lab1/dstFiles;.jpg;photo

2021-11-13 12:11 UTC, sqrtyyy commented on Antonov.Aleksei/lab1/CMakeLists.txt
> +add_executable(${PROJECT_NAME} daemon_main.cpp ${SRC})
main - не совсем исходник демона

2021-11-13 12:11 UTC, sqrtyyy commented on Antonov.Aleksei/lab1/daemon_main.cpp
> +    return EXIT_FAILURE;
Сделал

2021-11-13 12:13 UTC, sqrtyyy commented on Antonov.Aleksei/lab1/src/Daemon.cpp
> +    m_configParams.push_front(lineParams);
Мне не нужен доступ к случайному элементу контейнера за константу, я только итерируюсь по нему. Казалось бы, что лист - это то что мне нужно.

2021-11-18 20:16 UTC, kystyn commented on Antonov.Aleksei/lab1/src/Daemon.cpp
> +    m_configParams.push_front(lineParams);
Вы не совсем правы: операция инкремента итератора списка более трудоёмка, чем та же операция у массива, поскольку в массиве элементы располагаются в памяти линейно и, что называется, далеко ходить не надо. Однако это не является какой-то принципиальной ошибкой, просто учтите на будущее

2021-11-18 21:03 UTC, kystyn commented
1. копировать и перемещать -- разные вещи
2. очищать папку источник и папку приёмник -- разные вещи
3. при перечитывании конфига по SIGHUP-у в логе пишется ошибка перечитывания. по факту ничего не происходит
4. Попробовал запустить демона еще раз и также ничего не вышло, хотя конфиг валидный
5. заметил, что после редактирования размер увеличился на 1 байт, судя по диффу дело в символе перевода строки. сделайте так, чтобы конфиг с переводом строки в конце был валидным

2021-11-21 22:43 UTC, kystyn commented on Antonov.Aleksei/lab1/src/Daemon.cpp
> +    m_instance = new Daemon;
нигде

2021-11-21 22:44 UTC, kystyn commented
-2 балла за сроки, -2 за косяки, в т. ч. неустранённые
читайте внимательно условия, даже на последней итерации вы не выполнили все условия работы

2021-11-21 22:44 UTC, merged