LAB 2 Smirnova.daria
kystyn/OS_Labs_SPbPU_2021 pull request #27
Opened 2021-11-24 07:14 UTC by DariaWelt

2021-12-03 14:09 UTC, kystyn reviewed
Всё, что прислано работает. Я правильно понял, что вы хотите сдать только два метода взаимодействия? Напоминаю, будет 10 балов

2021-12-04 20:33 UTC, DariaWelt commented on Smirnova.Daria/lab2/Makefile
> +CFLAGS = -std=c++17 -Wall -Werror
исправила

2021-12-04 20:33 UTC, DariaWelt commented on Smirnova.Daria/lab2/connections/Connection.h
> +public:
исправила

2021-12-04 20:33 UTC, DariaWelt commented on Smirnova.Daria/lab2/client/Goat.h
> +    static Goat& getInstance(int hostPid);
исправила

2021-12-04 20:34 UTC, DariaWelt commented on Smirnova.Daria/lab2/connections/conn_seg.cpp
> +    std::ofstream ofs(m_connectionName);
Чтобы создать файл с таким путем, если его нет. После закрытия соединения я этот файл удаляю. Сделано все это потому что ftok ожидает путь до существующего и достижимого файла:

"The  ftok()  function  uses  the  identity  of the file named by the given pathname (which must refer to an existing, accessible file) and the least significant 8 bits of proj_id (which must be nonzero) to generate a key_t type System V IPC key, suitable for use with msgget(2), semget(2), or shmget(2)."

2021-12-04 21:48 UTC, kystyn requested changes

2021-12-04 21:48 UTC, kystyn commented on Smirnova.Daria/lab2/CMakeLists.txt
> +add_executable(host_mq utils/Message.h utils/ClientInfo.h utils/GameRules.h
не соответствует условиям: если добавится новый вид взаимодействия, скрипт надо будет дополнять

2021-12-04 21:48 UTC, kystyn commented on Smirnova.Daria/lab2/connections/Connection.h
> +    static Connection* createConnection();
всё правильно, только нужно ещё запривать конструктор (точнее, сделать protected), потому что иначе вы сможете создать экземпляр не фабричным методом, а конструктором

2021-12-05 07:23 UTC, DariaWelt commented on Smirnova.Daria/lab2/connections/Connection.h
> +    static Connection* createConnection();
не смогу создать, класс абстрактный. И не уверена, что нужно протектить конструкторы наследников. Не о них же идет речь?

2021-12-05 08:37 UTC, DariaWelt commented on Smirnova.Daria/lab2/CMakeLists.txt
> +add_executable(host_mq utils/Message.h utils/ClientInfo.h utils/GameRules.h
исправлено

2021-12-06 10:36 UTC, kystyn approved these changes

2021-12-06 10:36 UTC, kystyn commented on Smirnova.Daria/lab2/connections/Connection.h
> +    static Connection* createConnection();
Спасибо за пояснения, не обратил внимание на _= 0_. Действительно, я не вижу формальной причины  запрещать конструировать наследников через конструкторы, при том что базовый класс конструируется фабрично. Хотя интуитивно мне кажется неправильным разрешать фактически два метода создания одного и того же класса.

2021-12-06 10:36 UTC, merged