Anikin.Aleksandr lab2
kystyn/OS_Labs_SPbPU_2021 pull request #30
Opened 2021-11-28 18:58 UTC by Nika-Keks

Отправляю вторую лабораторную работу
Добавил ограничение на количество шагов игры, так как она может продолжаться очень долго

2021-12-14 22:30 UTC, kystyn requested changes
1. Много волков и один козёл? Не то, что просили UPD: тут всё правильно, я сначала не понял
2. Не видно самих чисел. Надо вывести
3. В логах error close file: Bad file descriptor
4.  а почему у меня один экзешник? и с каким типом взаимодействия?

2021-12-14 22:30 UTC, kystyn commented on Anikin/laba2/src/game.cpp
> +        static std::weak_ptr<synchronizer> inst();
smart pointer-ы круто!

2021-12-14 22:30 UTC, kystyn commented on Anikin/laba2/src/game.cpp
> +        return reinterpret_cast<void*>(-1);
Можно было бы конечно какой-нибудь енамчик

2021-12-14 22:30 UTC, kystyn commented on Anikin/laba2/src/game.cpp
> +        if (goatling._status && !hid(num, goatling._num, n_goatls))
хорошо бы печатать сами числа. у меня почему-то всегда побеждают козлы. очень подозрительно

2021-12-14 22:30 UTC, kystyn commented on Anikin/laba2/src/game.cpp
> +    pthread_create(&th, NULL, &wolf_thread, &(_args_blocks.back()));
почему у вас много волков?

2021-12-17 13:37 UTC, Nika-Keks commented
Исправил баг с закрытием файла, теперь в логах нет ошибок
Поправил генерацию случайных чисел и уменьшил количество игр до 3. Теперь выигрывают не только козлята
Вывел шаги игры
Енам для возвращаемых значений не сделал, если это необходимо, могу поправить

2021-12-17 15:46 UTC, kystyn commented
Лаба зачтена. 5/15 баллов

2021-12-17 15:47 UTC, kystyn approved these changes

2021-12-17 15:47 UTC, merged