Kuksenko.Kirill
kystyn/OS_Labs_SPbPU_2021 pull request #31
Opened 2021-11-30 09:59 UTC by kirillkuks

Add lab2, variant 9

2021-12-16 09:44 UTC, kystyn requested changes
В целом всё нормально, единственное что попрошу вместе с указанными правками выводить в хосте в std cout статусы (жив/мертв а не 0/1) и числа козлят и волка
Кроме того, я вижу сообщените client with pid ... can not wait host semaphore,значит завершение работает не совсем штатно. тоже надо разобраться

2021-12-16 09:44 UTC, kystyn commented on Kuksenko.Kirill/Lab2/connection/conn.h
> +    std::string name;
не может быть в общем для трёх типов соединения интерфейсе переменных, которые характерны только для одно из них. необходимо использовать механизм наследования

2021-12-16 09:44 UTC, kystyn commented on Kuksenko.Kirill/Lab2/host/host.cpp
> +        std::cout << "Invalid arguments" << std::endl;
хорошо бы подсказку для пользователя -- какие аргументы нужны

2021-12-16 09:44 UTC, kystyn commented on Kuksenko.Kirill/Lab2/host/wolf.cpp
> +        goat_status = new bool(wolf.chase_goat(message.goat_status, message.goat_number));
new bool??? зачем? и кто удалять будет?

2021-12-16 17:04 UTC, kirillkuks commented on Kuksenko.Kirill/Lab2/connection/conn.h
> +    std::string name;
Поправил

2021-12-16 17:04 UTC, kirillkuks commented on Kuksenko.Kirill/Lab2/host/host.cpp
> +        std::cout << "Invalid arguments" << std::endl;
Поправил

2021-12-16 17:07 UTC, kirillkuks commented on Kuksenko.Kirill/Lab2/host/wolf.cpp
> +        goat_status = new bool(wolf.chase_goat(message.goat_status, message.goat_number));
Мне нужен указатель, потому что я возвращаю статус козлёнка из кода, который выполняется в другой нити. Удалить забыл, теперь удаляю в самом хосте.

2021-12-16 17:30 UTC, kirillkuks commented
Исправил завершение работы. Изменил логику игры, до этого для каждого козлёнка волк выбрасывал разное число. Теперь на каждой итерации волк выбрасывает одно число для всех козлят. Вывожу статусы козлят, а также числа козлят и волка в std::cout.

2021-12-17 15:49 UTC, kystyn approved these changes

2021-12-17 16:15 UTC, merged