Ovechkin Danil Lab2 Var 4
kystyn/OS_Labs_SPbPU_2021 pull request #32
Opened 2021-12-05 15:58 UTC by OvechkinDanil

2021-12-16 10:54 UTC, kystyn requested changes
по работе всё хорошо. исправляйте замечания и будет зачёт

2021-12-16 10:54 UTC, kystyn commented on Ovechkin.Danil/lab2/client/goat.cpp
> +    if (sem_wait(sem) == -1) {
было требование про ожидание не более 5 секунд

2021-12-16 10:54 UTC, kystyn commented on Ovechkin.Danil/lab2/client/goat.cpp
> +        sleep(1);
Было требование ждать 5 секунд, пока клиент напишет хосту и наоборот, но не при подключении. Но даже в том формате, в котором это сделали вы, почему так странно -- 5 раз ждать по одной секунде?

2021-12-16 10:54 UTC, kystyn commented on Ovechkin.Danil/lab2/conn/conn.h
> +    void* shm;
переменные конкретных реализаций в общем интерфейсе. переделать

2021-12-16 10:54 UTC, kystyn commented on Ovechkin.Danil/lab2/client/goat.cpp
> +bool Goat::semSignal(sem_t* sem) {
у вас в двух разных классах одинаковые семантически функции semWait и semSignal. надо переделать

2021-12-16 10:54 UTC, kystyn commented on Ovechkin.Danil/lab2/CMakeLists.txt
> +foreach(TYPE_MODE mq seg fifo)
Каждый файл с расширением *.cpp (*.c,..) должен автоматически компилироваться в объектный файл без изменения CMakeLists

2021-12-17 11:41 UTC, OvechkinDanil commented on Ovechkin.Danil/lab2/CMakeLists.txt
> +foreach(TYPE_MODE mq seg fifo)
Исправил, но теперь пользователь может выбирать, какие взаимодействия будет использовать. Запускать скрипт теперь надо вот так: ./build.sh "fifo seg mq". К сожалению, другого спопособа не придумал, но зато выполнено условие, что нельзя менять CMakeLists

2021-12-17 11:42 UTC, OvechkinDanil commented on Ovechkin.Danil/lab2/client/goat.cpp
> +bool Goat::semSignal(sem_t* sem) {
Исправил

2021-12-17 11:42 UTC, OvechkinDanil commented on Ovechkin.Danil/lab2/conn/conn.h
> +    void* shm;
Исправил

2021-12-17 11:42 UTC, OvechkinDanil commented on Ovechkin.Danil/lab2/client/goat.cpp
> +    if (sem_wait(sem) == -1) {
Исправил

2021-12-17 11:42 UTC, OvechkinDanil commented on Ovechkin.Danil/lab2/client/goat.cpp
> +        sleep(1);
Исправил

2021-12-17 15:39 UTC, kystyn commented on Ovechkin.Danil/lab2/CMakeLists.txt
> +foreach(TYPE_MODE mq seg fifo)
Не было условия: не менять cmake при добавлении новых таргетов. было условие: не менять cmake, если в рамках текущей реализации вы добавляете новые файлы

2021-12-17 17:36 UTC, OvechkinDanil commented on Ovechkin.Danil/lab2/CMakeLists.txt
> +foreach(TYPE_MODE mq seg fifo)
Понял, исправлено

2021-12-17 21:40 UTC, kystyn approved these changes

2021-12-17 21:41 UTC, merged