Add lab2
kystyn/OS_Labs_SPbPU_2021 pull request #35
Opened 2021-12-07 22:19 UTC by MekhailS

2021-12-17 20:43 UTC, kystyn requested changes
CMake Error at CMakeLists.txt:14 (add_executable):
  Cannot find source file:

    //conn.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:14 (add_executable):
  No SOURCES given to target: client_fifo


CMake Error at CMakeLists.txt:18 (add_executable):
  No SOURCES given to target: host_sock


CMake Error at CMakeLists.txt:18 (add_executable):
  No SOURCES given to target: host_fifo


CMake Error at CMakeLists.txt:14 (add_executable):
  No SOURCES given to target: client_sock


CMake Error at CMakeLists.txt:18 (add_executable):
  No SOURCES given to target: host_mq


CMake Error at CMakeLists.txt:14 (add_executable):
  No SOURCES given to target: client_mq


CMake Generate step failed.  Build files cannot be regenerated correctly.
make: *** No targets specified and no makefile found.  Stop.
mv: cannot stat 'host*': No such file or directory
mv: cannot stat 'client*': No such file or directory

2021-12-17 20:43 UTC, kystyn commented on Shagvaliev.Mikhail/lab2/CMakeLists.txt
> +foreach(TYPE_MODE mq sock fifo)
CMakeLists не соответствует требованиям

2021-12-17 20:43 UTC, kystyn commented on Shagvaliev.Mikhail/lab2/conn/conn.h
> +    int _desc;
переменные конкретных реализаций в общем интерфейсе. переделать

2021-12-17 20:43 UTC, kystyn commented on Shagvaliev.Mikhail/lab2/conn/conn_sock.cpp
> +    _sockets = new int[2];
а зачем здесь аллоцировать память под два файловых дескриптора

2021-12-18 09:45 UTC, MekhailS commented
@kystyn По поводу пофейленного билда:
Как ни странно, но у себя я не могу это воспроизвести, не внося изменения в CMakeLists, все успешно билдится: 
```
sh build.sh
— The C compiler identification is GNU 9.3.0
— The CXX compiler identification is GNU 9.3.0
— Check for working C compiler: /usr/bin/cc
— Check for working C compiler: /usr/bin/cc — works
— Detecting C compiler ABI info
— Detecting C compiler ABI info - done
— Detecting C compile features
— Detecting C compile features - done
— Check for working CXX compiler: /usr/bin/c++
— Check for working CXX compiler: /usr/bin/c++ — works
— Detecting CXX compiler ABI info
— Detecting CXX compiler ABI info - done
— Detecting CXX compile features
— Detecting CXX compile features - done
— Configuring done
— Generating done
— Build files have been written to: /home/mikhail/CLionProjects/OS_Labs_SPbPU_2021/Shagvaliev.Mikhail/lab2/build
Scanning dependencies of target client_fifo
[ 4%] Building CXX object CMakeFiles/client_fifo.dir/client/client.cpp.o
[ 8%] Building CXX object CMakeFiles/client_fifo.dir/client/weather_predictor.cpp.o
[ 12%] Building CXX object CMakeFiles/client_fifo.dir/conn/conn_fifo.cpp.o
[ 16%] Linking CXX executable client_fifo
[ 16%] Built target client_fifo
Scanning dependencies of target host_sock
[ 20%] Building CXX object CMakeFiles/host_sock.dir/host/host.cpp.o
[ 25%] Building CXX object CMakeFiles/host_sock.dir/host/requestor.cpp.o
[ 29%] Building CXX object CMakeFiles/host_sock.dir/conn/conn_sock.cpp.o
[ 33%] Linking CXX executable host_sock
[ 33%] Built target host_sock
Scanning dependencies of target host_fifo
[ 37%] Building CXX object CMakeFiles/host_fifo.dir/host/host.cpp.o
[ 41%] Building CXX object CMakeFiles/host_fifo.dir/host/requestor.cpp.o
[ 45%] Building CXX object CMakeFiles/host_fifo.dir/conn/conn_fifo.cpp.o
[ 50%] Linking CXX executable host_fifo
[ 50%] Built target host_fifo
Scanning dependencies of target client_sock
[ 54%] Building CXX object CMakeFiles/client_sock.dir/client/client.cpp.o
[ 58%] Building CXX object CMakeFiles/client_sock.dir/client/weather_predictor.cpp.o
[ 62%] Building CXX object CMakeFiles/client_sock.dir/conn/conn_sock.cpp.o
[ 66%] Linking CXX executable client_sock
[ 66%] Built target client_sock
Scanning dependencies of target host_mq
[ 70%] Building CXX object CMakeFiles/host_mq.dir/host/host.cpp.o
[ 75%] Building CXX object CMakeFiles/host_mq.dir/host/requestor.cpp.o
[ 79%] Building CXX object CMakeFiles/host_mq.dir/conn/conn_mq.cpp.o
[ 83%] Linking CXX executable host_mq
[ 83%] Built target host_mq
Scanning dependencies of target client_mq
[ 87%] Building CXX object CMakeFiles/client_mq.dir/client/client.cpp.o
[ 91%] Building CXX object CMakeFiles/client_mq.dir/client/weather_predictor.cpp.o
[ 95%] Building CXX object CMakeFiles/client_mq.dir/conn/conn_mq.cpp.o
[100%] Linking CXX executable client_mq
[100%] Built target client_mq
```

Получить данную ошибку у меня получается, если изменить 10 строку CMakeLists следующим образом:
`set(CONN conn)` -> `set(CONN)`


Лог:
```
sh build.sh
— The C compiler identification is GNU 9.3.0
— The CXX compiler identification is GNU 9.3.0
— Check for working C compiler: /usr/bin/cc
— Check for working C compiler: /usr/bin/cc — works
— Detecting C compiler ABI info
— Detecting C compiler ABI info - done
— Detecting C compile features
— Detecting C compile features - done
— Check for working CXX compiler: /usr/bin/c++
— Check for working CXX compiler: /usr/bin/c++ — works
— Detecting CXX compiler ABI info
— Detecting CXX compiler ABI info - done
— Detecting CXX compile features
— Detecting CXX compile features - done
— Configuring done
CMake Error at CMakeLists.txt:14 (add_executable):
Cannot find source file:

//conn.h

Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
.hpp .hxx .in .txx

CMake Error at CMakeLists.txt:14 (add_executable):
No SOURCES given to target: client_fifo

CMake Error at CMakeLists.txt:18 (add_executable):
No SOURCES given to target: host_sock

CMake Error at CMakeLists.txt:18 (add_executable):
No SOURCES given to target: host_fifo

CMake Error at CMakeLists.txt:14 (add_executable):
No SOURCES given to target: client_sock

CMake Error at CMakeLists.txt:18 (add_executable):
No SOURCES given to target: host_mq

CMake Error at CMakeLists.txt:14 (add_executable):
No SOURCES given to target: client_mq

CMake Generate step failed. Build files cannot be regenerated correctly.
make: *** No targets specified and no makefile found. Stop.
mv: cannot stat 'host*': No such file or directory
mv: cannot stat 'client*': No such file or directory
```

Возможно ли такое, что set некорректно сработал?

2021-12-18 09:55 UTC, MekhailS commented on Shagvaliev.Mikhail/lab2/conn/conn_sock.cpp
> +    _sockets = new int[2];
В целом, это два дескриптора для двух сокетов:
[0] — listener, который хендлит входящие соединения, по сути, необходим только для сервера. 
[1] — дескриптор сокета непосредственно для обмена данными.

Источник:
https://en.wikipedia.org/wiki/Berkeley_sockets#:~:text=Server%5Bedit%5D-,Establishing,-a%20TCP%20server

2021-12-18 11:31 UTC, MekhailS commented
Изменил CMakeLists, добавил классы реализаций интерфейса Conn

2021-12-19 12:32 UTC, kystyn commented on Shagvaliev.Mikhail/lab2/conn/conn_sock.cpp
> +    _sockets = new int[2];
Это понятно
Зачем аллоцировать динамическую память?
Почему не статическая?

2021-12-19 12:34 UTC, kystyn approved these changes

2021-12-19 12:35 UTC, kystyn commented on Shagvaliev.Mikhail/lab2/conn/conn_sock.cpp
> +    _sockets = new int[2];
Незначительный недочёт, так что пофиг

2021-12-19 12:35 UTC, merged