Voinova.Alyona Lab2 Var15
kystyn/OS_Labs_SPbPU_2021 pull request #39
Opened 2021-12-17 13:28 UTC by pikabol88

2021-12-17 22:15 UTC, kystyn requested changes
всё хорошо, только как выйти?

2021-12-17 22:15 UTC, kystyn commented on Voinova.Alyona/lab2/conn/IConn.h
> +    int _id;
частные переменные в общем интерфейсе

2021-12-17 22:15 UTC, kystyn commented on Voinova.Alyona/lab2/host/Host.h
> +    static const std::string _month;
у вас и так синглтон. зачем статики?

2021-12-21 19:28 UTC, pikabol88 commented on Voinova.Alyona/lab2/host/Host.h
> +    static const std::string _month;
справедливо, испралено

2021-12-21 19:29 UTC, pikabol88 commented
Добавлена команда exit для выхода

2021-12-22 10:28 UTC, kystyn approved these changes

2021-12-22 10:29 UTC, merged